Account for trip IDs missing shape IDs
Andrew-Dickinson/nyct-gtfs pull request #3
Opened 2023-11-06 14:23 UTC by tolidano

When the shape ID is missing, the direction
cannot be parsed. It shows up as a 0 after _

Fixes #2

2023-11-24 02:57 UTC, Andrew-Dickinson requested changes
Thanks for the contribution, bummer that this field is sometimes not provided. I'm curious to hear if this was a one-off event for an unusual service pattern or if you noticed it continuing over time?

Just two small tweaks and we can get this merged. Also could you bump the version in `setup.py` to `1.3.1` in preparation for release?

2023-11-24 02:57 UTC, Andrew-Dickinson commented on nyct_gtfs/trip.py
> +        parts = self.shape_id.split('.')
```suggestion
        if not self.shape_id:
            return None
        parts = self.shape_id.split('.')
```

2023-11-24 02:57 UTC, Andrew-Dickinson commented on nyct_gtfs/trip.py
> +        if '..' in self.trip_id:
```suggestion
        if '..' in self.shape_id:
```

2023-11-24 02:57 UTC, Andrew-Dickinson commented on nyct_gtfs/trip.py
> +        if '..' in self.trip_id:
Honestly this condition should have been based on `shape_id` from the beginning

2023-11-24 02:57 UTC, Andrew-Dickinson commented on nyct_gtfs/trip.py
> +        parts = self.shape_id.split('.')
Just to cover the new edge case introduced by the changes in `self.shape_id` above

2023-11-28 03:52 UTC, tolidano commented
I have bumped setup and made the requested changes. It has happened at least three times since I have been watching it but after the second time, I put guardrails in my own code to account for it, so I'm not sure if it has happened again since.

2023-11-28 03:53 UTC, tolidano commented
I would also note that your library is extremely valuable even for non-nyct feeds, and I am using it for other feeds beyond the subway. I intend to utilize it (if possible) for LIRR, MNR, NJT, and more.

2023-12-02 03:38 UTC, Andrew-Dickinson approved these changes

2023-12-02 03:52 UTC, Andrew-Dickinson commented
LGTM. For what it's worth this appears to have happened for at least one Northbound 2 train this morning, the GTFS trip ID was `050350_0`, so definitely happy to have this fixed

2023-12-02 03:53 UTC, merged

2023-12-02 04:10 UTC, Andrew-Dickinson commented
FYI, noticed and fixed a regression from a small syntax issue. Take `1.3.2` to avoid issues